name: PlatformIO CI

on:  
  push:  
    branches: [main, develop]  # Runs on pushes to these branches  
  pull_request:  
    branches: [main, develop]  # Runs on PRs targeting these branches  

jobs:  
  test:  
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  # Fetches your repo  

      - name: Install PlatformIO  
        run: pip install platformio  

      - name: Run Unit Tests  
        run: pio test -e native  # Run tests in the 'native' environment