name: PlatformIO CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Set Up Udev Rules
      run: |
        wget https://raw.githubusercontent.com/platformio/platformio-core/develop/scripts/99-platformio-udev.rules
        sudo cp 99-platformio-udev.rules /etc/udev/rules.d/
        sudo udevadm control --reload-rules
        sudo udevadm trigger

    - name: Run PlatformIO Tests (Micro)
      run: pio test -e micro